#!/bin/sh
set -eu

# Generates badapple.asm from prebuilt ASCII frames in the bad-apple-ascii submodule.
# Default behavior includes all frames; you can cap with MAX_FRAMES for smaller outputs.
#
# Usage:
#   ./generate_badapple_asm.sh
#   MAX_FRAMES=300 ./generate_badapple_asm.sh
#   OUT=badapple_full.asm ./generate_badapple_asm.sh

FRAMES_DIR="${FRAMES_DIR:-bad-apple-ascii/frames-ascii}"
OUT="${OUT:-badapple.asm}"
MAX_FRAMES="${MAX_FRAMES:-0}"
START_FRAME="${START_FRAME:-1}"
DEBUG="${DEBUG:-0}"
PROGRESS_EVERY="${PROGRESS_EVERY:-250}"

timestamp() {
    date '+%H:%M:%S'
}

log_info() {
    printf '[%s] [INFO] %s\n' "$(timestamp)" "$*"
}

log_debug() {
    if [ "$DEBUG" = "1" ]; then
        printf '[%s] [DEBUG] %s\n' "$(timestamp)" "$*"
    fi
}

log_error() {
    printf '[%s] [ERROR] %s\n' "$(timestamp)" "$*" >&2
}

START_TS="$(date +%s)"

if [ "$PROGRESS_EVERY" -le 0 ] 2>/dev/null; then
    log_error "PROGRESS_EVERY must be a positive integer"
    exit 1
fi

if [ "$START_FRAME" -le 0 ] 2>/dev/null; then
    log_error "START_FRAME must be a positive integer"
    exit 1
fi

log_info "Starting badapple assembly generation"
log_debug "FRAMES_DIR=$FRAMES_DIR"
log_debug "OUT=$OUT"
log_debug "MAX_FRAMES=$MAX_FRAMES"
log_debug "START_FRAME=$START_FRAME"
log_debug "PROGRESS_EVERY=$PROGRESS_EVERY"

if [ ! -d "$FRAMES_DIR" ]; then
    log_error "frames directory not found: $FRAMES_DIR"
    exit 1
fi

TMP_BASE="$(mktemp -d)"
cleanup() {
    rm -rf "$TMP_BASE"
}

on_interrupt() {
    log_error "Interrupted, cleaning up temporary files"
    cleanup
    exit 130
}

trap cleanup EXIT
trap on_interrupt INT TERM

FRAME_LIST="$TMP_BASE/frame_list.txt"
DATA_FILE="$TMP_BASE/frame_data.asm"
TABLE_FILE="$TMP_BASE/frame_table.asm"

# Natural-sort frame files like out0001.jpg.txt ...
log_info "Indexing frame files"
find "$FRAMES_DIR" -type f -name '*.txt' | LC_ALL=C sort -V > "$FRAME_LIST"

TOTAL="$(wc -l < "$FRAME_LIST" | tr -d ' ')"
if [ "$TOTAL" -eq 0 ]; then
    log_error "no .txt frames found in $FRAMES_DIR"
    exit 1
fi

log_info "Discovered $TOTAL frame file(s)"

if [ "$MAX_FRAMES" -gt 0 ] 2>/dev/null; then
    COUNT="$MAX_FRAMES"
else
    COUNT=$((TOTAL - START_FRAME + 1))
fi

if [ "$START_FRAME" -gt "$TOTAL" ]; then
    log_error "START_FRAME ($START_FRAME) is beyond total frames ($TOTAL)"
    exit 1
fi

AVAILABLE=$((TOTAL - START_FRAME + 1))
if [ "$COUNT" -gt "$AVAILABLE" ]; then
    COUNT="$AVAILABLE"
fi

END_FRAME=$((START_FRAME + COUNT - 1))

log_info "Will process $COUNT frame(s), range: $START_FRAME..$END_FRAME"

: > "$DATA_FILE"
: > "$TABLE_FILE"
log_debug "Temporary files initialized under $TMP_BASE"

INDEX=0
SELECTED=0
LAST_FRAME=""
while IFS= read -r FRAME_PATH; do
    INDEX=$((INDEX + 1))

    if [ "$INDEX" -lt "$START_FRAME" ]; then
        continue
    fi

    if [ "$SELECTED" -ge "$COUNT" ]; then
        break
    fi

    SELECTED=$((SELECTED + 1))

    LAST_FRAME="$FRAME_PATH"

    LABEL="frame_$(printf '%04d' "$SELECTED")"

    {
        printf '%s:\n' "$LABEL"

        # Escape backslash and double-quote for NASM db strings.
        sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' "$FRAME_PATH" |
        while IFS= read -r LINE || [ -n "$LINE" ]; do
            printf '    db "%s", 13, 10\n' "$LINE"
        done

        printf '    db 0\n\n'
    } >> "$DATA_FILE"

    printf '    dw %s\n' "$LABEL" >> "$TABLE_FILE"

    if [ $((SELECTED % PROGRESS_EVERY)) -eq 0 ] || [ "$SELECTED" -eq "$COUNT" ]; then
        log_info "Progress: $SELECTED/$COUNT frames generated"
        log_debug "Latest frame: $LAST_FRAME -> $LABEL"
    fi
done < "$FRAME_LIST"

log_info "Writing assembly output to $OUT"

cat > "$OUT" <<EOF
; badapple.asm - autogenerated from $FRAMES_DIR
; Generated by generate_badapple_asm.sh
; Frame count: $COUNT
;
; NOTE:
;   This file can become very large when using all frames.
;   If assembly size/addressing becomes a problem, regenerate with MAX_FRAMES.
;
[BITS 16]
[ORG 0xA000]

SYSCALL_INT equ 0x80
SYS_PUTS equ 0x02
SYS_CLEAR equ 0x05

FRAME_COUNT equ $COUNT
DELAY_OUTER equ 45
DELAY_INNER equ 9000

start:
    mov ax, 0x10
    mov ds, ax
    mov es, ax

    mov si, msg_title
    call sys_clear
    call sys_puts
    call delay

    mov cx, FRAME_COUNT
    mov bx, frame_table

.play_loop:
    call sys_clear

    mov si, [bx]
    add bx, 2
    call sys_puts
    call delay

    loop .play_loop

    call sys_clear
    ret

delay:
    push bx
    push cx

    mov cx, DELAY_OUTER
.d1:
    mov bx, DELAY_INNER
.d2:
    dec bx
    jnz .d2
    loop .d1

    pop cx
    pop bx
    ret

sys_puts:
    mov ah, SYS_PUTS
    int SYSCALL_INT
    ret

sys_clear:
    mov ah, SYS_CLEAR
    int SYSCALL_INT
    ret

msg_title:
    db "Bad Apple ASCII (autogenerated)", 13, 10
    db "Frames: $COUNT", 13, 10, 13, 10, 0

frame_table:
EOF

cat "$TABLE_FILE" >> "$OUT"
printf '\n' >> "$OUT"
cat "$DATA_FILE" >> "$OUT"

OUT_SIZE_BYTES="$(wc -c < "$OUT" | tr -d ' ')"
OUT_LINES="$(wc -l < "$OUT" | tr -d ' ')"
END_TS="$(date +%s)"
DURATION="$((END_TS - START_TS))"

log_info "Generated $OUT with $COUNT frame(s) from $FRAMES_DIR"
log_info "Output stats: ${OUT_SIZE_BYTES} bytes, ${OUT_LINES} lines, ${DURATION}s"
