#!/usr/bin/env python3
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "still-alive.py"
OUT = ROOT / "stillalive_data.inc"


def db_bytes_literal(s: str, add_nul: bool = True) -> str:
    vals = [str(ord(ch)) for ch in s]
    if add_nul:
        vals.append("0")
    return "    db " + ", ".join(vals)


def parse_source(path: Path):
    tree = ast.parse(path.read_text(encoding="utf-8"))

    arts = {}
    lyrics = None
    credits = None

    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            name = node.targets[0].id
            if name.startswith("a") and name[1:].isdigit():
                arts[name] = ast.literal_eval(node.value)
            elif name == "credits":
                credits = ast.literal_eval(node.value)
            elif name == "lyrics":
                if not isinstance(node.value, ast.List):
                    raise ValueError("lyrics is not a list")
                parsed = []
                for elt in node.value.elts:
                    if not isinstance(elt, ast.Call) or not isinstance(elt.func, ast.Name) or elt.func.id != "lyric":
                        raise ValueError("Unexpected lyrics element")
                    if len(elt.args) != 4:
                        raise ValueError("Unexpected lyric arg count")
                    w = ast.literal_eval(elt.args[0])
                    t = ast.literal_eval(elt.args[1])
                    interval = ast.literal_eval(elt.args[2])
                    mode = ast.literal_eval(elt.args[3])
                    parsed.append((w, t, interval, mode))
                lyrics = parsed

    ordered_arts = [arts[f"a{i}"] for i in range(1, 11)]
    if credits is None or lyrics is None:
        raise ValueError("Failed to parse credits/lyrics")

    return ordered_arts, credits, lyrics


def build_assets(arts, credits, lyrics):
    # Unique text pool for mode 0/1 lyrics
    text_to_label = {}
    texts = []

    events = []
    for idx, (word, t_cs, interval, mode) in enumerate(lyrics):
        next_time = lyrics[idx + 1][1] if idx + 1 < len(lyrics) else t_cs

        str_label = "0"
        art_index = 0xFF
        delay_ms = 0

        if mode in (0, 1):
            s = str(word)
            if s not in text_to_label:
                label = f"lyric_text_{len(texts)}"
                text_to_label[s] = label
                texts.append((label, s))
            str_label = text_to_label[s]

            char_count = len(s)
            if char_count == 0:
                char_count = 1

            if float(interval) < 0:
                per_char_sec = ((next_time - t_cs) / 100.0) / char_count
            else:
                per_char_sec = float(interval) / char_count

            delay_ms = int(round(per_char_sec * 1000.0))
            if delay_ms < 0:
                delay_ms = 0
        elif mode == 2:
            art_index = int(word)

        events.append({
            "time": int(t_cs),
            "mode": int(mode),
            "art": int(art_index),
            "text": str_label,
            "delay_ms": int(delay_ms),
        })

    lines = []
    lines.append("; auto-generated by tools/gen_stillalive_assets.py")
    lines.append("STILLALIVE_ART_COUNT equ 10")
    lines.append(f"STILLALIVE_EVENT_COUNT equ {len(events)}")
    lines.append(f"STILLALIVE_CREDITS_LEN equ {len(credits)}")
    lines.append("")

    for i, art in enumerate(arts):
        lines.append(f"art_{i}:")
        for row in art:
            lines.append(db_bytes_literal(row, add_nul=True))
        lines.append("")

    lines.append("art_table:")
    for i in range(len(arts)):
        lines.append(f"    dw art_{i}")
    lines.append("")

    for label, text in texts:
        lines.append(f"{label}:")
        lines.append(db_bytes_literal(text, add_nul=True))
    lines.append("")

    lines.append("credits_text:")
    lines.append(db_bytes_literal(credits, add_nul=True))
    lines.append("")

    lines.append("; event layout:")
    lines.append("; dw time_cs, db mode, db art_index(0xFF if none), dw text_ptr(0 if none), dw char_delay_ms")
    lines.append("lyric_events:")
    for ev in events:
        lines.append(f"    dw {ev['time']}")
        lines.append(f"    db {ev['mode']}")
        lines.append(f"    db {ev['art']}")
        lines.append(f"    dw {ev['text']}")
        lines.append(f"    dw {ev['delay_ms']}")

    return "\n".join(lines) + "\n"


def main():
    arts, credits, lyrics = parse_source(SRC)
    data = build_assets(arts, credits, lyrics)
    OUT.write_text(data, encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
